name: cas
channels:
  - anaconda
  - conda-forge
  - defaults
  - SimpleITK
  - pytorch
dependencies:
  - python=3.6
  - numpy=1.15.4
  - kdtree=0.16
  - matplotlib=3.0.2
  - pydicom=1.2.1
  - pytorch=1.4.0
  - torchvision=0.5.0
  - cudatoolkit=10.1
  - tqdm=4.42.1
  - nibabel=3.0.1
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - SimpleITK=1.2.0
  - vtk=8.2.0
  - pip=20.0.2
  - pip:
      - transformations==2018.10.18
